server: #random port
  port: 0

spring:
  application:
    name: video-service

###### maria db 설정 관련 추가 #####

# h2 database setting - 사용하지 않을 시, 주석 처리
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
#    username: sa
#    password: null

# Eureka client 등록 (Naming server에 service 등록) - 추후 microservices 연결 시 변경 필요
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false   # client 등록 시, true로 값 변경 필요
    fetch-registry: false         # client 등록 시, true로 값 변경 필요
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka   # eureka 서버 주소로 변경 필요

# application.yml 에 저장된 값을 읽어 REST API를 테스트하기 위한 dummy data
greeting:
  message: Welcome to the FairyTail!